### ISSUE TITLE
updating to rillig/sfntly.git (from googlei18n/sfntly.git)

### ISSUE THREAD

**Issue by ghost** [bdusell/webfont-generator#13]
hi,
`googlei18n/sfntly` is an archive for their old code,
the new code is placed in `https://github.com/rillig/sfntly.git`
(and I think it uses the same folder structure)

**Comment by bdusell** [comment]
Thanks for the heads-up! I wonder if we can get #6 fixed. I'll see about updating `setup`.

**Comment by ghost** [comment]
let me check,
I'm currently working on trying to convert few fonts anyway...
I might as well see if this alternative source will help with it.. :]

```sh

fetch_sfntly() {
  if [[ ! -d $SFNTLY_DIR ]]; then
    log 'Fetching sfntly...'
#   git clone https://github.com/googlei18n/sfntly.git "$SFNTLY_DIR"
    git clone https://github.com/rillig/sfntly.git "$SFNTLY_DIR"
...
...
...

```

**Comment by ghost** [comment]
ok.

slightly modified the setup for sfntly from https://github.com/rillig/sfntly.git
which uses maven instead of Ant.
so first:
```sh
fetch_sfntly() {
  if [[ ! -d $SFNTLY_DIR ]]; then
    log 'Fetching sfntly...'
#   git clone https://github.com/googlei18n/sfntly.git "$SFNTLY_DIR"
    git clone "https://github.com/rillig/sfntly.git" "$SFNTLY_DIR"
  fi
}
.......
```
and 
```sh

build_sfntly() {
  log 'Building sfntly...'
  (cd "$SFNTLY_DIR"/java && mvn compile)
}
......
```
and 
```sh
main() {
  require_command 'git' &&
  require_command 'java' &&
  require_command 'javac' &&
  require_command 'mvn' &&
.........
```

next, after maven-building sfntly, the `Font.class` and `FontFactory.class` will be placed in 
`webfont-generator-master/vendor/sfntly/java/target/classes/com/google/typography/font/sfntly`
so `webfont-generator-master/src/java/Makefile` will be:
```sh
ConvertFont.class: ConvertFont.java
	javac -cp .:../../vendor/sfntly/java/target/classes/com/google/typography/font/sfntly $<
.......
```
compiled with linux Mint. seems fine. 


(or http://central.maven.org/maven2/com/jaredrummler/sfntly/1.0.1/sfntly-1.0.1.jar )

**Comment by bdusell** [comment]
Great, feel free to submit a pull request.

**Comment by ghost** [comment]
...I avoid pull requests like the plague ;)

**Comment by bdusell** [comment]
Leaving this open until I integrate this change.
