### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jackhill** [bdusell/webfont-generator#17]
What is the license of this project?

Thanks!

**Comment by bdusell** [comment]
Good question. I would like to use MIT, but I need to review the licenses of the third-party tools.

**Comment by jackhill** [comment]
Thanks, makes sense.

**Comment by ghost** [comment]
sfntly    - <a href="https://github.com/rillig/sfntly/blob/master/cpp/COPYING.txt">Apache2</a>.
woff2     - <a href="https://github.com/google/woff2/blob/master/LICENSE">MIT</a>.
FontForge - <a href="https://github.com/fontforge/fontforge/blob/master/LICENSE">GNU GPL 3+ / revised BSD license</a>

licensing usually goes by the most limiting one,
which is GNU GPL 3, but FontForge is not really distributed,
so it can be ignored :]

MIT is the same as Apache (Apache is <a href="https://choosealicense.com/">a bit more permissive</a>), 

so you might as well choose MIT.

**Comment by bdusell** [comment]
Thanks for the research, @eladkarako! Technically none of the libraries are "distributed" except insofar as the `setup` script downloads and compiles their source code, as is the case with snftly and woff2. Anyway, given the fact that FontForge is simply assumed to be installed on the host system, according to the terms of GNU GPLv3, there is no need for the terms of the license to be propagated to webfont-generator.

The license of the project will be MIT.
