### ISSUE TITLE
python3 not installed

### ISSUE THREAD

**Issue by tieroneco** [bdusell/webfont-generator#19]
Whenever I run ./setup It's saying python3 is not installed, I have installed python36 and also checked with python30 none of these is working. I am on WIN7 x64
![image](https://user-images.githubusercontent.com/21085049/41843820-1b6b6584-788c-11e8-9324-1ab0d6c54907.png)

**Comment by bdusell** [comment]
I have not tested the setup process in mingw, though I guess that qualifies as a *nix system. There is a PEP ([here](https://www.python.org/dev/peps/pep-0394/)) which says that `python3` should be an alias to Python 3, though I'm not sure that applies here. You did install Python 3 within the mingw environment, correct?

As a workaround I recommend adding a symlink to `~/bin` from `python3` to your Python 3 executable.

**Comment by tieroneco** [comment]
I have renamed the python.exe to python3.exe and it worked.
