### ISSUE TITLE
please indicate all the packages that must be installed in beforehand

### ISSUE THREAD

**Issue by CrimsonFork** [bdusell/webfont-generator#21]
It was a little frustrating to find the next missing dependency only *after* I installed the previous one. Also indicating the actual package names would be helpful as well.

`default-jdk default-jre fontforge git make maven python3`

**Comment by bdusell** [comment]
I try to keep the setup script distro-agnostic, but a list of packages for Ubuntu in the documentation would probably be pretty helpful for most people. I actually wrote up a Dockerfile for setting up on Ubuntu 18.04 a while back that shows exactly what packages need to be installed: https://github.com/bdusell/webfont-generator/issues/18#issuecomment-398627636

Would it have been more convenient if the setup script had listed all of the missing commands at once?

**Comment by CrimsonFork** [comment]
Not even necessarily commands (although, appreciated, I almost installed some unrelated package with "mvn" in it), looking up works just fine, but it'd be nice if the dependencies, even as they are shown, would be shown at once.

It's not like a huge deal, but also installing jre, to only then install jdk (could've guessed, but still), to then install maven, etc. is kinda unoptimal.

Btw, thanks for the software, it's really nice.

On 11 June 2020 22:15:38 GMT+02:00, Brian DuSell <notifications@github.com> wrote:
>I try to keep the setup script distro-agnostic, but a list of packages for Ubuntu in the documentation would probably be pretty helpful for most people. I actually wrote up a Dockerfile for setting up on Ubuntu 18.04 a while back that shows exactly what packages need to be installed: https://github.com/bdusell/webfont-generator/issues/18#issuecomment-398627636
>
>Would it have been more convenient if the setup script had listed all of the missing commands at once?
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bdusell/webfont-generator/issues/21#issuecomment-642904897
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
