### ISSUE TITLE
Won't accept .woff2 files as input

### ISSUE THREAD

**Issue by onassar** [bdusell/webfont-generator#5]
Sometimes our users submit woff2 files, and we want to convert them to `woff` files (to ensure they're available in all browsers). Currently your library doesn't support this, but I think it would help in this edge-case.

**Comment by bdusell** [comment]
Hm, that's strange, it should support conversion from woff to woff2. What is the error message?

**Comment by onassar** [comment]
Apologies I mistyped.
I mean using a `woff2` input file.

Here's the error:

    21:12  vm2  ubuntu@local [~/webfont-generator] : ./bin/generate-webfonts -o assets _formats/woff2.woff2
    Unrecognized format 'woff2'.

**Comment by bdusell** [comment]
Okay, it looks like this would be a good thing to support. FontForge doesn't read woff2, but Google's woff2 library does come with a woff2-ttf converter, so that should do the trick. It's just a matter of modifying the main Python script to make use of it.

**Comment by onassar** [comment]
Great to hear

**Comment by onassar** [comment]
Great I'll test this soon. I've been directly decompressing in the interim, so it's nice to potentially not have to do this.
